//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicXAutomationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientSymptom
    {
        public int PatientSymptomID { get; set; }
        public int PatientID { get; set; }
        public int SymptomID { get; set; }
    
        public virtual patient patient { get; set; }
        public virtual symptom symptom { get; set; }
    }
}
