//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicXAutomationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PODrugLine
    {
        public int POId { get; set; }
        public int PODrugId { get; set; }
        public int DrugId { get; set; }
        public int Qty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string orderStatus { get; set; }
    
        public virtual drug drug { get; set; }
        public virtual POHeader POHeader { get; set; }
    }
}
