//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicXAutomationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prescription
    {
        public int prescriptionID { get; set; }
        public Nullable<int> adviceID { get; set; }
        public Nullable<int> drugID { get; set; }
        public string dosage { get; set; }
        public string note { get; set; }
    
        public virtual advice advice { get; set; }
        public virtual drug drug { get; set; }
    }
}
